FORMAT: 1A
HOST: https://api.otr-ratte.de/v2

# OTR-Ratte
This is the official documentation for OTR-Ratte.de

## Status Codes
Every api-call can respond one of the following http-status codes:
<table>
<tr><th>Code</th><th>Description</th></tr>
<tr><td>200</td><td>Success</td></tr>
<tr><td>403</td><td>Forbidden (check logon fields; for more information check "Account", "Info")</td></tr>
<tr><td>404</td><td>Not Found (check sent otrkey)</td></tr>
</table>

## Contact
You need a new API method or found a bug? Contact me via mail: support@otr-ratte.de

## Group Account
### Info [/account/info{?user,password}]
+ Parameters
    + user (string) ... e-Mail-Address
    + password (string) ... Password as md5 hash

#### Account Information [GET]
Returns account information including the donator-duration in days (field `donator`).
+ Request JSON
    + Headers

            Accept: application/json

+ Response 200 (application/json)

        {
            "donator": 123
        }

+ Response 403 (application/json)

        {
            "error": "invalid login"
        }

+ Request XML
    + Headers

            Accept: application/xml

+ Response 200 (application/xml)

        <?xml version="1.0"?>
        <response>
            <donator>123</donator>
        </response>

+ Response 403 (application/xml)

        <?xml version="1.0"?>
        <response>
            <error>invalid login</error>
        </response>

## Group Otrkey
### Read [/otrkey/read{?type,user,password,otrkey}]
#### Otrkey Information [GET]
Returns information about the given `otrkey`.
+ Parameters
    + type (string)
        Response Type
        + Values
            + `xml`
            + `json`
    + user (string) ... e-Mail-Address
    + password (string) ... Password as md5 hash
    + otrkey (string) ... otrkey-name (some_file.otrkey)

+ Response 200 (application/json)

        {
            "size": 1531398256,
            "otrEpgId": 9669758
        }

+ Response 200 (application/xml)

        <?xml version="1.0"?>
        <response>
            <size>1531398256</size>
            <otrEpgId>9669758</otrEpgId>
        </response>

+ Response 404 (application/json)

        {
            "error": "otrkey not found"
        }

+ Response 404 (application/xml)

        <?xml version="1.0"?>
        <response>
            <error>otrkey not found</error>
        </response>

### Find [/otrkey/find{?type,user,password,string}]
#### Otrkey Files [GET]
Searches for otrkey-files.
+ Parameters
    + type (string)
        Response Type
        + Values
            + `xml`
            + `json`
    + user (string) ... e-Mail-Address
    + password (string) ... Password as md5 hash
    + string (string) ... search string (parts of otrkey)

+ Response 200 (application/json)

        {
            "results": [
                {
                    "otrkey": "20_Jahre_Feste_Silbereisen_feiert_14.10.25_20-15_ard_180_TVOON_DE.mpg.HQ.avi.otrkey"
                },
                {
                    "otrkey": "Akte_D_14.10.20_23-30_ard_45_TVOON_DE.mpg.HQ.avi.otrkey"
                },
                {
                    "otrkey": "Akte_D_14.10.27_23-45_ard_45_TVOON_DE.mpg.HQ.avi.otrkey"
                }
            ]
        }

+ Response 200 (application/xml)

        <?xml version="1.0"?>
        <response>
            <results>
                <result>
                    <otrkey>20_Jahre_Feste_Silbereisen_feiert_14.10.25_20-15_ard_180_TVOON_DE.mpg.HQ.avi.otrkey</otrkey>
                </result>
                <result>
                    <otrkey>Akte_D_14.10.20_23-30_ard_45_TVOON_DE.mpg.HQ.avi.otrkey</otrkey>
                </result>
                <result>
                    <otrkey>Akte_D_14.10.27_23-45_ard_45_TVOON_DE.mpg.HQ.avi.otrkey</otrkey>
                </result>
            </results>
        </response>

